export enum IconName {
  visibleOn = 'visibleOn',
  filter = 'filter',
  visibleOff = 'visibleOff',
  logout = 'logout',
  back = 'back',
  burger = 'burger',
  right = 'right',
  close = 'close',
  dropdownArrow = 'dropdownArrow',
  forward = 'forward',
  backward = 'backward',
  calendar = 'calendar',
  settings = 'settings',
  tableArrowUp = 'tableArrowUp',
  tableArrowDown = 'tableArrowDown',
  time = 'time',
  showMore = 'showMore',
  download = 'download',
  remove = 'remove',
  upload = 'upload',
  layer = 'layer',
  leftArrow = 'leftArrow',
  rightArrow = 'rightArrow',
}
